broken refactor: attempt to clean up http interface
defined http request and response structs... but running into an issue
with defining headers which has been frustrating. need to read about
this to finish testing this out.

```
cc ./tst/test_http.c ./src/http.c `pkg-config --cflags --libs json-c` `pkg-config --cflags --libs libcurl` -o ./tst/test_http
./tst/test_http.c:32:16: error: initialization of flexible array member is not allowed
   32 |     .headers = { "Accept: application/json", "Content-Type: application/json" }
      |                ^
./tst/../src/http.h:31:9: note: initialized flexible array member 'headers' is here
   31 |   char *headers[];
      |         ^
1 error generated.
```